use std::env;
use std::fs;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
use std::path::Path;
use std::process::Command;
use std::io;

pub fn install_hook() -> Result<(), io::Error> {
    let hook_path = Path::new(".git/hooks/post-commit");
    
    // Determine the command to run.
    // Ideally this points to the absolute path of the binary,
    // but for dev/portable purposes, we might want to check if 'git-gotchi' is in PATH.
    // For now, let's assume 'git-gotchi' will be in the PATH.
    let script_content = r#"#!/bin/sh
# Git-Gotchi Hook
# This script was generated by git-gotchi

git-gotchi feed
"#;

    fs::write(hook_path, script_content)?;

    #[cfg(unix)]
    {
        let mut perms = fs::metadata(hook_path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(hook_path, perms)?;
    }

    Ok(())
}

pub struct CommitStats {
    pub files_changed: u32,
    pub insertions: u32,
    pub deletions: u32,
}

impl CommitStats {
    pub fn total_lines(&self) -> u32 {
        self.insertions + self.deletions
    }
}

pub fn get_commit_stats() -> Result<CommitStats, io::Error> {
    let output = Command::new("git")
        .args(["diff", "--shortstat", "HEAD~1", "HEAD"])
        .output()?;

    if !output.status.success() {
        return Err(io::Error::new(io::ErrorKind::Other, "Git command failed"));
    }

    let output_str = String::from_utf8_lossy(&output.stdout);
    // Example output: " 1 file changed, 15 insertions(+), 5 deletions(-)"
    // Or empty if no changes (e.g. merge commit)

    let parts: Vec<&str> = output_str.trim().split(',').collect();
    
    let mut files = 0;
    let mut insertions = 0;
    let mut deletions = 0;

    for part in parts {
        let part = part.trim();
        if part.contains("file changed") || part.contains("files changed") {
            if let Some(num) = part.split_whitespace().next() {
                 files = num.parse().unwrap_or(0);
            }
        } else if part.contains("insertion") {
             if let Some(num) = part.split_whitespace().next() {
                 insertions = num.parse().unwrap_or(0);
            }
        } else if part.contains("deletion") {
             if let Some(num) = part.split_whitespace().next() {
                 deletions = num.parse().unwrap_or(0);
            }
        }
    }

    Ok(CommitStats {
        files_changed: files,
        insertions,
        deletions,
    })
}
